name: make test url
on: 
  pull_request:
    branches: 
      - 'develop'
    types:
      - opened
jobs:
  - name: 'Setup Cloud SDK'
    uses: 'google-github-actions/setup-gcloud@v0'
    with:
      project_id: '${{ env.GCP_PROJECT_ID }}'
      service_account_key: '${{ secrets.GCP_SA_KEY }}'

  - name: 'Deploy to App Engine'
    run: 'gcloud app deploy app.yaml --quiet --no-promote --version v1'