name: make_develop
on: 
  pull_request:
    branches: 
      - develop

jobs:
  deplay-staging:
    name: GAE deplay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: yarn install
      - name: Build
        run: yarn build

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0.3.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
          promote: false
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: v1

      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'