name: make_develop
on: 
  pull_request:
    types:
       - opened
       - reopened
    branches: 
      - develop

jobs:
  deplay-staging:
    name: GAE deplay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          project_id: '${{ env.PROJECT_ID }}'
          service_account_key: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Deploy to App Engine'
        run: 'gcloud app deploy app.yaml --quiet --no-promote --version v1'

      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'