name: make test URL
on: 
  pull_request:
    branches: 
      - develop
      - main
    types: [opened, synchronize]

jobs:
  deplay-staging:
    name: GAE deplay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn install
      - name: Build
        run: yarn build

      - name: auth
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Deploy to App Engine for Test URL'
        id: deploy-to-webapp
        run: gcloud app deploy --no-promote

      - name: comment-pr
        uses: JoseThen/comment-pr@v1.1.1
        with:
          comment: 'Preview ${{ steps.deploy-to-webapp.outputs }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}